import { NextResponse } from "next/server";
import { writeFile, readFile } from "fs/promises";
import { existsSync } from "fs";
import path from "path";

// Backend directory and config file path
const BACKEND_DIR = process.env.BACKEND_DIR || "/Users/zhuhe/Cursor/deepagents";
const CONFIG_FILE = path.join(BACKEND_DIR, "model_config.json");

interface EnabledTools {
  fetch_url?: boolean;
  // SerpAPI tools
  serpapi_search?: boolean;
  // Exa tools
  exa_search?: boolean;
  exa_contents?: boolean;
  exa_find_similar?: boolean;
  exa_answer?: boolean;
  exa_research?: boolean;
  // Tavily tools
  tavily_search?: boolean;
  tavily_extract?: boolean;
  tavily_map?: boolean;
  tavily_crawl?: boolean;
  perplexity_search?: boolean;
  perplexity_chat?: boolean;
}

interface ModelConfig {
  provider: string;
  model: string;
  api_key: string;
  base_url: string | null;
  model_overrides?: {
    subagents?: { [key: string]: string | null };
    summarization?: string | null;
    suggestions?: string | null;
  } | null;
  serp_api_key?: string;
  exa_api_key?: string;
  tavily_api_key?: string;
  perplexity_api_key?: string;
  enabled_tools?: EnabledTools;
  _last_updated?: string;
  _comment?: string;
}

/**
 * GET /api/backend/config - Read current config
 */
export async function GET() {
  try {
    if (!existsSync(CONFIG_FILE)) {
      return NextResponse.json({
        config: null,
        message: "Config file not found",
      });
    }

    const content = await readFile(CONFIG_FILE, "utf-8");
    const config = JSON.parse(content);

    return NextResponse.json({
      config,
      path: CONFIG_FILE,
    });
  } catch (error) {
    console.error("[CONFIG API] Error reading config:", error);
    return NextResponse.json(
      {
        error: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 }
    );
  }
}

/**
 * POST /api/backend/config - Save config to file
 */
export async function POST(request: Request) {
  try {
    const body = await request.json();
    
    // Build config object
    const config: ModelConfig = {
      provider: body.provider || "",
      model: body.model || "",
      api_key: body.api_key || "",
      base_url: body.base_url || null,
      model_overrides: body.model_overrides || null,
      serp_api_key: body.serp_api_key || undefined,
      exa_api_key: body.exa_api_key || undefined,
      tavily_api_key: body.tavily_api_key || undefined,
      perplexity_api_key: body.perplexity_api_key || undefined,
      enabled_tools: body.enabled_tools || undefined,
      _last_updated: new Date().toISOString(),
      _comment: "Auto-generated by frontend. Edit via Settings UI.",
    };

    // Write to file
    await writeFile(CONFIG_FILE, JSON.stringify(config, null, 2), "utf-8");

    console.log(`[CONFIG API] Saved config: provider=${config.provider}, model=${config.model}`);

    return NextResponse.json({
      success: true,
      message: "Config saved. Restart backend to apply changes.",
      config,
      path: CONFIG_FILE,
    });
  } catch (error) {
    console.error("[CONFIG API] Error saving config:", error);
    return NextResponse.json(
      {
        success: false,
        error: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 }
    );
  }
}

